# check: where to put file e.g .github/workflows/tests.yml

name: tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov mypy ruff

      - name: Lint
        run: ruff check .

      - name: Type check
        run: mypy .

      - name: Run tests
        run: pytest -q --disable-warnings --maxfail=1
